### ISSUE TITLE
Can't use Order::model()->find($orderId);

### ISSUE THREAD

**Issue by bintzandt** [afosto/shopctrl#18]
When I try to request the data for one specific order I get the following error:
> An uncaught Exception was encountered
> Type: Afosto\Bp\Exceptions\ValidationException
> Message: Model Afosto\ShopCtrl\Models\int not found
> Filename: vendor/afosto/bp/src/Components/Validator.php
> Line Number: 149
> 
> Backtrace:
> File: vendor/afosto/bp/src/Components/Model.php
> Line: 148
> Function: getNewModel
> 
> File: vendor/afosto/shopctrl/src/Models/Order.php
> Line: 188
> Function: setAttributes
> 
> File: vendor/afosto/shopctrl/src/Components/Operations/Find.php
> Line: 44
> Function: setAttributes

I have tried to fix the error myself but I have to admit that I am having trouble understanding how the code is intertwined. This error (presumably) also prevents me from getting all order information when I use `Order::model()->findAll()`. Only the following attributes get retrieved correctly 
```php
  ["id"]=>
  int(118955)
  ["orderCode"]=>
  string(14) "test1530020452"
  ["date"]=>
  string(19) "2018-06-26T15:40:52"
  ["orderTotalIncVat"]=>
  float(5)
  ["orderTotalExVat"]=>
  float(0)
  ["currencyId"]=>
  int(0)
  ["currencyCode"]=>
  string(3) "EUR"
  ["deleted"]=>
  bool(false)
  ["changeTimestamp"]=>
  string(23) "2018-06-26T15:40:54.497"
  ["mainStatusId"]=>
  int(1)
  ["affiliateId"]=>
  NULL
```
All other possible order attributes are `NULL`. Can you help me fix this error? (I assume that this also effects your own business negatively.) Or am I just doing something wrong?

**Comment by TerraSkye** [comment]
i've proposed a fix for the issue.
https://github.com/afosto/shopctrl/pull/19

**Comment by bakkerpeter** [comment]
Issue has been resolved, thanks for reporting!
